spring:
  application:
    name: App
  datasource:
    url: ${DB_URL:jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db.migration

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        max_fetch_depth: 5
